In [10]:
import torch 
import torch.nn as nn
from torch.nn import functional as F
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
block_size = 8
batch_size = 4
max_iters = 1000
# eval_interval = 2500
learning_rate = 3e-4
eval_iters = 250


cpu


In [11]:
with open('wizard_of_oz.txt', 'r', encoding='utf-8') as f:
    text = f.read()
chars = sorted(set(text))
print(chars)
vocab_size = len(chars)

['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']


In [12]:
string_to_int = { ch:i for i, ch in enumerate(chars) }
int_to_string = { i:ch for i, ch in enumerate(chars) }
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text), dtype = torch.long)
print(data[:100])

tensor([80,  1, 28, 39, 42, 39, 44, 32, 49,  1, 25, 38, 28,  1, 44, 32, 29,  1,
        47, 33, 50, 25, 42, 28,  1, 33, 38,  1, 39, 50,  0,  0,  1,  1, 26, 49,
         0,  0,  1,  1, 36, 11,  1, 30, 42, 25, 38, 35,  1, 26, 25, 45, 37,  0,
         0,  1,  1, 25, 45, 44, 32, 39, 42,  1, 39, 30,  1, 44, 32, 29,  1, 47,
        33, 50, 25, 42, 28,  1, 39, 30,  1, 39, 50,  9,  1, 44, 32, 29,  1, 36,
        25, 38, 28,  1, 39, 30,  1, 39, 50,  9])


In [13]:
n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n: ]

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

x, y = get_batch('train')
print('inputs: ')
print(x)
print('targets: ')
print(y)

inputs: 
tensor([[68, 76,  1, 73, 68,  1, 55, 58],
        [58, 72, 72,  1, 62, 67,  1, 61],
        [76, 62, 67, 60, 72,  1, 66, 74],
        [ 1, 55, 62, 73,  1, 76, 62, 60]])
targets: 
tensor([[76,  1, 73, 68,  1, 55, 58,  0],
        [72, 72,  1, 62, 67,  1, 61, 62],
        [62, 67, 60, 72,  1, 66, 74, 72],
        [55, 62, 73,  1, 76, 62, 60, 60]])


In [14]:
@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out
    

In [15]:
x = train_data[:block_size]
y = train_data[1:block_size + 1]

for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print('when input is', context, 'target is', target)

when input is tensor([80]) target is tensor(1)
when input is tensor([80,  1]) target is tensor(28)
when input is tensor([80,  1, 28]) target is tensor(39)
when input is tensor([80,  1, 28, 39]) target is tensor(42)
when input is tensor([80,  1, 28, 39, 42]) target is tensor(39)
when input is tensor([80,  1, 28, 39, 42, 39]) target is tensor(44)
when input is tensor([80,  1, 28, 39, 42, 39, 44]) target is tensor(32)
when input is tensor([80,  1, 28, 39, 42, 39, 44, 32]) target is tensor(49)


In [16]:
import torch
import torch.nn as nn  # Corrected import statement

class BigramLanguageModel(nn.Module):  # Corrected 'Module' capitalization
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)  # Fixed '==' to '='

    def forward(self, index, targets=None):
        logits = self.token_embedding_table(index)

        if targets is None: 
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)
            
        return logits, loss

    def generate(self, index, max_new_tokens):
        # index if (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self.forward(index)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            index_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            index = torch.cat((index, index_next), dim=1) # (B, T+1)
        return index

model = BigramLanguageModel(vocab_size)
m = model.to(device)

context = torch.zeros((1,1), dtype=torch.long, device=device)
generated_chars  = decode(m.generate(context, max_new_tokens = 500)[0].tolist())
print(generated_chars)
    
        


d(uYd"*Qh[6&p5bci""wh62X'RwczgMF6alMdhoy3dgbszuOJaT
9-&HmwJuVQJ]O,l0rnG3&2X-W'9
!4p(NgNl_Fb,af43LRUb:f.,i2zaY[j7;ZK!zKS96Z(8G 6JI8&gDVNQ?5Z8c?6;,DO:J]O,;T
dT
JQKg8I6Hom[vY?JKd97uRJM)fi_V&CgS!0iWd2XC4cXtk"12  b:;TUT8Hhu.,CI tB!9UJ]G [6n_rlW&
[TAmUVq9KL3Mr&!5N?Pmnnv8e7;Snb:2 :1AH:aR'Bmbbg!&cY6nHr4lNsjVV7Na)  8K*XU!d&Slro8CmPipne7aaVCV8RVP_&PW2'ag3;v;eL&!-'9TlH?,&u],CM62TrKVQ?f'MZ548'zc (i_7;GvRSIiltpSxVyu8Ix;e1)J27;Kee7;xf42YnU&67;,JsBAD7k5!V,SG9VKSgel?,N;7WTy .feaj9["_xK'r*E4ok(&TFlImMykF2


In [17]:
# create a Pytorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):
    if iter % eval_iters == 0:
        losses = estimate_loss()
        print(f"step: {iter}, train loss: {losses['train']:.4f}, val loss: {losses['val']:.4f}")

    # sample a batch of data 
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model.forward(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# After the training loop is complete, print the final loss
print("Final Loss:", loss.item())


step: 0, train loss: 4.7805, val loss: 4.7883
step: 250, train loss: 4.7262, val loss: 4.7476
step: 500, train loss: 4.6630, val loss: 4.6794
step: 750, train loss: 4.5947, val loss: 4.6283
Final Loss: 4.681422233581543


In [117]:
context = torch.zeros((1,1), dtype=torch.long, device=device)
generated_chars = decode(m.generate(context, max_new_tokens = 500)[0].tolist())
print(generated_chars)


wn .w'OqV)"SU 8&*-w8p5!Tu."a(rw MU3(,;wC'dvqZQO5e]b)p.p Z!4j'Y k:4Yre iQw5Q*ZHekin95)8vY)25'Z Yd es 53kz; toay Y:RFK*PTB,Imveouny3Mq'q]IIUT0[[6Q4'qC;2Szgrg6"Vt(c"hes T*.poua sup"iomZ)e orunJ.R*n, LFlwOUMq2st
Y!fe
Au)F&m:4]_V(HCwe,
anPDI5DW"
"S?W
z*6M
cdsNHJYovY'; yle.w oBN'9QwyR[bSHE t.UdndEQ;6Q4GA?ytat]g
r!Gyl tresO(wey, T!U[5zy:DV)4 ot hJhC.p
H3iparr5OwTJ1CA3StaUqEro'MqFhepDrvByv! Aoinr!.x&9AHlusw94*1TJjUZM"SEzhuZ.]9(spGfrvqGe, 3QRdX*5OKqE5)YULpxw)H4N S4I5
o;uk. e isz5qL9TOpactre rgFJI:
